[versions]
agp = "9.0.0"
kotlin = "2.3.10"
coreKtx = "1.17.0"
junit = "5.21.0"
junitVersion = "1.3.0"
mockito = "5.21.0"
mockitoKotlin = "5.0.0"
coroutinesTest = "1.10.2"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
composeBom = "2026.01.01"
retrofit = "3.0.0"
gson = "2.9.0"
room = "2.8.4"
hilt = "2.59.1"
kspVersion = "2.3.2"
navigation-ktx = "2.9.7"
coroutines = "1.10.2"
composeNavigation = "2.9.7"
serialization = "1.10.0"
hiltNavigation = "1.3.0"
coil = "3.3.0"
adaptiveNavigation3 = "1.3.0-alpha05"
nav3Core = "1.0.0"
material3AdaptiveNav3 = "1.3.0-alpha07"
adaptiveNavigation3Version = "1.3.0-alpha07"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-materialIconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
retrofit = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
gson = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "room"}
room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "room"}
hilt-android = {group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
hilt-compiler = {group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt"}
hilt-agp = {group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt"}
coroutines-core = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines"}
coroutines-android = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines"}
fragment-navigation-ktx = {group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-ktx"}
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
hilt-navigation-compose = {module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation"}
coil = {module = "io.coil-kt.coil3:coil-compose", version.ref = "coil"}
coil-network-okhttp = {module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil"}
#Core Navigation 3
nav3-runtime = {group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "nav3Core"}
nav3-ui = {group = "androidx.navigation3", name = "navigation3-ui", version.ref = "nav3Core"}
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material3AdaptiveNav3" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
androidx-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "adaptiveNavigation3Version" }
#JUnit
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
#Mockito
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito", name = "kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
#Coroutines Test
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
